[features]
seeds = false
[programs.localnet]
mysolanaapp = "AR553gCnpmdsWtxt3xs7ZGiaTdHrNf4c8RENqftWXrj7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/hp/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
